import turtle
p = turtle.Turtle()
s=turtle.Screen()
s.bgcolor("yellow")
p.fillcolor("red")
p.begin_fill()
p.hideturtle()
p.circle(100)
p.penup()
p.left(270)
p.forward(100)
p.pendown()
p.left(90)
p.circle(200)
p.end_fill()
turtle.done()