import turtle
import math
p=turtle.Turtle()
s=turtle.Screen()
def state():
    p.penup()
    p.forward(-200)
    p.pendown()
    p.pencolor("black")
    s.bgcolor("white")
def curve(t):
    a1=math.degrees(math.asin(100/t))
    p.left(360-a1)
    p.circle(t,2*a1)
    p.right(30)
    p.left(30)
    p.circle(-t,2*a1)
    p.left(a1)
def circleatc(r):
    p.penup()
    p.right(90)
    p.forward(r)
    p.left(90)
    p.pendown()
    p.circle(r)
    p.penup()
    p.left(90)
    p.forward(r)
    p.pendown()
    p.right(90)
    p.right(90)


state()
#curve()
init=p.position()
p.penup()
p.forward(200)
p.left(90)
p.forward(200/math.sqrt(3))
p.fillcolor("#C10000")
p.begin_fill()
circleatc(400/math.sqrt(3))
p.end_fill()
p.penup()
p.setposition(init)
p.pendown()
p.fillcolor("black")
p.begin_fill()
for i in range(0,3):
    curve(110)
    p.left(120)
p.end_fill()
p.penup()
p.forward(200)
p.left(90)
p.forward(200/math.sqrt(3))
p.fillcolor("#C10000")
p.begin_fill()
circleatc(40)
p.end_fill()
center=(p.xcor(),p.ycor())
turtle.done()

