import turtle
import math
p=turtle.Turtle()
s=turtle.Screen()
u=100
def state():
    p.speed(0)
    p.penup()
    p.hideturtle()
    p.left(90)
    p.penup()
    p.forward(100)
    p.pendown()
    p.right(90)
    p.pendown()
    p.pencolor("white")
    s.bgcolor("black")
def curve(t):
    a1=math.degrees(math.asin(u/(2*t)))
    p.left(360-a1)
    p.circle(t,2*a1)
    p.right(30)
    p.left(30)
    p.circle(-t,2*a1)
    p.left(a1)
def circleatc(r):
    p.penup()
    p.right(90)
    p.forward(r)
    p.left(90)
    p.pendown()
    p.circle(r)
    p.penup()
    p.left(90)
    p.forward(r)
    p.pendown()
    p.right(90)
    p.right(90)
state()
p1=p.position()
pf=(p1[0]-u,p1[1]-(u/math.sqrt(3)))
#curve()
for i in range(0,700):
    if (i%6==0):
        p.pencolor(1-i/1000,0,0)
    if (i%6==1):
       p.pencolor(1-i/1000,1-i/1000,1-i/1000)
    if (i%6==2):
      p.pencolor(1-i/1000,0,0)
    if (i%6==3):
      p.pencolor(1-i/1000,1-i/1000,1-i/1000)
    if (i%6==4):
      p.pencolor(1-i/1000,0,0)
    if (i%6==5):
      p.pencolor(1-i/1000,1-i/1000,1-i/1000)
    p.forward(1.5*i)
    #p.circle((math.log(1+i)+i)/2)
    p.left(90.99)
p.penup()
p.setposition(pf)
p.setheading(0)
p.pendown()
p.pencolor("black")
init=p.position()
p.penup()
p.forward(u)
p.left(90)
p.forward(u/math.sqrt(3))
p.fillcolor("#C10000")
p.begin_fill()
circleatc(2*u/math.sqrt(3))
p.end_fill()
p.penup()
p.setposition(init)
p.pendown()
p.fillcolor("black")
p.begin_fill()
for i in range(0,3):
    curve(u*(0.55))
    p.left(120)
p.end_fill()
p.penup()
p.forward(u)
p.left(90)
p.forward(u/math.sqrt(3))
p.fillcolor("#C10000")
p.begin_fill()
circleatc(u/5)
p.end_fill()
center=(p.xcor(),p.ycor())
turtle.done()